const courses = [
  // TIL KURSLARI (4 ta)
  {
    id: 1,
    category: "Til kurslari",
    title: "Ingliz tili",
    instructor: "Teacher Abdulloh",
    image: "/assets/courses/course-img-1.jpg",
    duration: "6 oy",
    students: "2.4K",
    rating: "4.9",
    price: "200 000 so'm",
  },
  {
    id: 2,
    category: "Til kurslari",
    title: "Rus tili",
    instructor: "Ivan Petrov",
    image: "/assets/courses/course-img-2.jpg",
    duration: "5 oy",
    students: "1.8K",
    rating: "4.8",
    price: "180 000 so'm",
  },
  {
    id: 5,
    category: "Til kurslari",
    title: "IELTS Intensive",
    instructor: "Teacher Abdulloh",
    image: "/assets/courses/course-img-4.jpg",
    duration: "3 oy",
    students: "1.5K",
    rating: "5.0",
    price: "300 000 so'm",
  },
  {
    id: 6,
    category: "Til kurslari",
    title: "CEFR C1",
    instructor: "Teacher Abdulloh",
    image: "/assets/courses/course-img-3.jpg",
    duration: "4 oy",
    students: "900",
    rating: "4.9",
    price: "280 000 so'm",
  },

  // ANIQ FANLAR (3 ta)
  {
    id: 3,
    category: "Aniq fanlar",
    title: "Matematika",
    instructor: "Ali Karimov",
    image: "/assets/courses/course-img-1.jpg",
    duration: "4 oy",
    students: "3.2K",
    rating: "4.9",
    price: "220 000 so'm",
  },
  {
    id: 8,
    category: "Aniq fanlar",
    title: "Fizika",
    instructor: "Bekzod Rahimov",
    image: "/assets/courses/course-img-2.jpg",
    duration: "4 oy",
    students: "1.9K",
    rating: "4.8",
    price: "230 000 so'm",
  },
  {
    id: 9,
    category: "Aniq fanlar",
    title: "Kimyo",
    instructor: "Dilnoza Axmedova",
    image: "/assets/courses/course-img-4.jpg",
    duration: "4 oy",
    students: "1.4K",
    rating: "4.7",
    price: "220 000 so'm",
  },

  // IT KURSLAR (4 ta)
  {
    id: 4,
    category: "IT kurslar",
    title: "Frontend React",
    instructor: "Sarah Johnson",
    image: "/assets/courses/course-img-3.jpg",
    duration: "5 oy",
    students: "2.1K",
    rating: "4.8",
    price: "350 000 so'm",
  },
  {
    id: 10,
    category: "IT kurslar",
    title: "Backend Node.js",
    instructor: "John Smith",
    image: "/assets/courses/course-img-2.jpg",
    duration: "6 oy",
    students: "1.6K",
    rating: "4.8",
    price: "370 000 so'm",
  },
  {
    id: 11,
    category: "IT kurslar",
    title: "UI/UX Design",
    instructor: "Emily Clark",
    image: "/assets/courses/course-img-4.jpg",
    duration: "3 oy",
    students: "1.2K",
    rating: "4.9",
    price: "300 000 so'm",
  },
  {
    id: 12,
    category: "IT kurslar",
    title: "Python Programming",
    instructor: "Michael Brown",
    image: "/assets/courses/course-img-1.jpg",
    duration: "5 oy",
    students: "2.3K",
    rating: "4.9",
    price: "340 000 so'm",
  },

  // IJTIMOIY FANLAR (2 ta)
  {
    id: 13,
    category: "Ijtimoiy fanlar",
    title: "Tarix",
    instructor: "Sardor Islomov",
    image: "/assets/courses/course-img-4.jpg",
    duration: "4 oy",
    students: "1.3K",
    rating: "4.7",
    price: "200 000 so'm",
  },
  {
    id: 14,
    category: "Ijtimoiy fanlar",
    title: "Huquq",
    instructor: "Aziza Nurmatova",
    image: "/assets/courses/course-img-2.jpg",
    duration: "3 oy",
    students: "800",
    rating: "4.8",
    price: "210 000 so'm",
  },

  // IMTIHON TAYYORLOV (3 ta)
  {
    id: 15,
    category: "Imtihon tayyorlov",
    title: "IELTS Full Course",
    instructor: "Teacher Abdulloh",
    image: "/assets/courses/course-img-2.jpg",
    duration: "4 oy",
    students: "2K",
    rating: "5.0",
    price: "320 000 so'm",
  },
  {
    id: 16,
    category: "Imtihon tayyorlov",
    title: "CEFR B2",
    instructor: "Teacher Abdulloh",
    image: "/assets/courses/course-img-1.jpg",
    duration: "3 oy",
    students: "1.1K",
    rating: "4.9",
    price: "270 000 so'm",
  },
  {
    id: 17,
    category: "Imtihon tayyorlov",
    title: "DTM tayyorlov",
    instructor: "Ali Karimov",
    image: "/assets/courses/course-img-2.jpg",
    duration: "6 oy",
    students: "2.5K",
    rating: "4.8",
    price: "250 000 so'm",
  },

  // MAKTAB TAYYORLOV (2 ta)
  {
    id: 18,
    category: "Maktab tayyorlov",
    title: "1-4 sinf umumiy",
    instructor: "Dilafruz Xasanova",
    image: "/assets/courses/course-img-3.jpg",
    duration: "6 oy",
    students: "1.7K",
    rating: "4.8",
    price: "180 000 so'm",
  },
  {
    id: 19,
    category: "Maktab tayyorlov",
    title: "Prezident maktabi",
    instructor: "Ali Karimov",
    image: "/assets/courses/course-img-2.jpg",
    duration: "5 oy",
    students: "900",
    rating: "4.9",
    price: "300 000 so'm",
  },

  // KASBIY RIVOJLANISH (2 ta)
  {
    id: 20,
    category: "Kasbiy rivojlanish",
    title: "SMM Marketing",
    instructor: "Shohruh",
    image: "/assets/courses/course-img-1.jpg",
    duration: "2 oy",
    students: "1.2K",
    rating: "4.9",
    price: "350 000 so'm",
  },
  {
    id: 21,
    category: "Kasbiy rivojlanish",
    title: "Copywriting",
    instructor: "Azizbek",
    image: "/assets/courses/course-img-2.jpg",
    duration: "2 oy",
    students: "700",
    rating: "4.8",
    price: "300 000 so'm",
  },

  // BOLALAR KURSLARI (1 ta)
  {
    id: 22,
    category: "Bolalar kurslari",
    title: "Kids English",
    instructor: "Teacher Abdulloh",
    image: "/assets/courses/course-img-4.jpg",
    duration: "6 oy",
    students: "2K",
    rating: "4.9",
    price: "180 000 so'm",
  },
];

export default courses;


import {
  GraduationCap,
  BookOpen,
  Users,
  Award,
  Code2,
  Megaphone,
  Globe,
  PenTool,
  Languages,
  Star,
} from "lucide-react"

export const teachers = [
  {
    id: 1,
    name: "Abdulloh Rahmatullayev",
    role: "CEO & Co-Founder",
    badge: "CEO & Co-Founder",
    image: "/teachers/teacher-1.jpg",
    bio: "Ta’lim va turli biznes loyihalar asoschisi. Zamonaviy ta’lim tizimini rivojlantirish ustida ishlaydi.",
    stats: [
      { icon: GraduationCap, label: "tajriba", value: "5+ yil" },
      { icon: Users, label: "o‘quvchi bilan ishlagan", value: "10,000+" },
    ],
    socials: {
      telegram: "#",
      instagram: "#",
      linkedin: "#",
    },
  },
  {
    id: 2,
    name: "Kaxxarov Akmaljon",
    role: "Co-Founder & Investor",
    badge: "Investor",
    image: "/teachers/teacher-2.jpg",
    bio: "Ta’lim loyihalarini qo‘llab-quvvatlash va platforma o‘sishiga hissa qo‘shadi.",
    stats: [
      { icon: Award, label: "loyihalar investori", value: "Ko‘plab" },
      { icon: Globe, label: "ijtimoiy loyihalar", value: "Faol" },
    ],
    socials: {
      telegram: "#",
      instagram: "#",
      linkedin: "#",
    },
  },
  {
    id: 3,
    name: "Najmiddin",
    role: "CIO & Co-Founder",
    badge: "CIO & Co-Founder",
    image: "/teachers/teacher-3.jpg",
    bio: "Platformaning texnik arxitekturasi, funksionalligi va barqaror ishlashini ta’minlaydi.",
    stats: [
      { icon: Code2, label: "developer", value: "Full-stack" },
      { icon: Code2, label: "boshqaruvi", value: "Backend/Frontend" },
    ],
    socials: {
      telegram: "#",
      instagram: "#",
      linkedin: "#",
    },
  },
  {
    id: 4,
    name: "Nilufar Ergasheva",
    role: "English Teacher",
    badge: "IELTS Mentor",
    image: "/teachers/teacher-4.jpg",
    bio: "IELTS va General English yo‘nalishida o‘quvchilarga natijaga yo‘naltirilgan dars beradi.",
    stats: [
      { icon: Languages, label: "IELTS daraja", value: "8.0" },
      { icon: Users, label: "o‘quvchi", value: "500+" },
    ],
    socials: {
      telegram: "#",
      instagram: "#",
      linkedin: "#",
    },
  },
  {
    id: 5,
    name: "Shaxriyor Karimov",
    role: "Marketing Lead",
    badge: "Marketing Lead",
    image: "/teachers/teacher-5.jpg",
    bio: "Bilimgoh brendi, reklama strategiyasi va foydalanuvchilar bilan aloqani rivojlantiradi.",
    stats: [
      { icon: Megaphone, label: "kampaniya", value: "50+" },
      { icon: Users, label: "auditoriya", value: "50K+" },
    ],
    socials: {
      telegram: "#",
      instagram: "#",
      linkedin: "#",
    },
  },
  {
    id: 6,
    name: "Sevinch Ibrohimova",
    role: "Community Lead",
    badge: "Community Lead",
    image: "/teachers/teacher-6.jpg",
    bio: "Hamjamiyat bilan ishlash va foydalanuvchi tajribasini yaxshilash bo‘yicha mas’ul.",
    stats: [
      { icon: Users, label: "hamjamiyat", value: "20+" },
      { icon: Star, label: "tajriba", value: "3+ yil" },
    ],
    socials: {
      telegram: "#",
      instagram: "#",
      linkedin: "#",
    },
  },
  {
    id: 7,
    name: "Azizbek Rasulov",
    role: "Math Teacher",
    badge: "Matematika",
    image: "/teachers/teacher-7.jpg",
    bio: "Matematika va mantiqiy fikrlash bo‘yicha kuchli metodikaga ega ustoz.",
    stats: [
      { icon: BookOpen, label: "kurslar", value: "12+" },
      { icon: Users, label: "o‘quvchi", value: "700+" },
    ],
    socials: {
      telegram: "#",
      instagram: "#",
      linkedin: "#",
    },
  },
  {
    id: 8,
    name: "Madina Sobirova",
    role: "Russian Teacher",
    badge: "Rus tili",
    image: "/teachers/teacher-8.jpg",
    bio: "Rus tilini sodda, amaliy va bosqichma-bosqich o‘rgatishga ixtisoslashgan.",
    stats: [
      { icon: Languages, label: "tajriba", value: "4+ yil" },
      { icon: BookOpen, label: "darslar", value: "300+" },
    ],
    socials: {
      telegram: "#",
      instagram: "#",
      linkedin: "#",
    },
  },
  {
    id: 9,
    name: "Javohir Aliyev",
    role: "IT Mentor",
    badge: "Frontend Mentor",
    image: "/teachers/teacher-9.jpg",
    bio: "Frontend dasturlash, React va zamonaviy web texnologiyalar bo‘yicha mentor.",
    stats: [
      { icon: Code2, label: "texnologiya", value: "React" },
      { icon: Users, label: "shogird", value: "200+" },
    ],
    socials: {
      telegram: "#",
      instagram: "#",
      linkedin: "#",
    },
  },
  {
    id: 10,
    name: "Gulnoza Tursunova",
    role: "Writing Mentor",
    badge: "Writing Expert",
    image: "/teachers/teacher-10.jpg",
    bio: "Academic writing, essay structure va imtihon yozuvlariga tayyorlash bo‘yicha mutaxassis.",
    stats: [
      { icon: PenTool, label: "writing", value: "C1+" },
      { icon: Award, label: "natija", value: "High score" },
    ],
    socials: {
      telegram: "#",
      instagram: "#",
      linkedin: "#",
    },
  },
]